from typing import Protocol
from uuid import UUID

from app.modules.account.models import PasswordResetTokenRecord, PendingRegistration, RefreshTokenRecord, User


class UserRepository(Protocol):
    def get_by_id(self, user_id: UUID) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def email_exists(self, email: str, exclude_user_id: UUID | None = None) -> bool: ...
    def create(self, user: User) -> User: ...
    def update(self, user: User) -> User: ...
    def delete(self, user_id: UUID) -> None: ...
    def update_password(self, user_id: UUID, password_hash: str) -> None: ...
    def update_theme(self, user_id: UUID, theme: str) -> User: ...


class PendingRegistrationRepository(Protocol):
    def create(self, registration: PendingRegistration) -> PendingRegistration: ...
    def get_by_id(self, registration_id: UUID) -> PendingRegistration | None: ...
    def update(self, registration: PendingRegistration) -> PendingRegistration: ...
    def delete(self, registration_id: UUID) -> None: ...


class RefreshTokenRepository(Protocol):
    def create(self, record: RefreshTokenRecord) -> RefreshTokenRecord: ...
    def get_by_hash(self, token_hash: str) -> RefreshTokenRecord | None: ...
    def revoke(self, token_hash: str) -> None: ...
    def revoke_all_for_user(self, user_id: UUID) -> None: ...


class PasswordResetTokenRepository(Protocol):
    def create(self, record: PasswordResetTokenRecord) -> PasswordResetTokenRecord: ...
    def get_by_hash(self, token_hash: str) -> PasswordResetTokenRecord | None: ...
    def mark_used(self, token_hash: str) -> None: ...
