from datetime import date
from typing import Protocol
from uuid import UUID

from app.modules.travel_buddies.models import (
    Group,
    GroupMember,
    MemberRole,
    Poll,
    PollOption,
    PollStatus,
    PollVote,
    Message,
    Attachment,
    Task,
    TaskStatus,
    PackingItem,
)


class GroupRepository(Protocol):
    def get_by_id(self, group_id: UUID) -> Group | None: ...
    def get_by_name(self, name: str) -> Group | None: ...
    def create(self, group: Group) -> Group: ...
    def update(self, group: Group) -> Group: ...
    def delete(self, group_id: UUID) -> None: ...


    def list_for_user(self, user_id: UUID, limit: int, offset: int) -> list[Group]: ...
    def count_for_user(self, user_id: UUID) -> int: ...


    def search(self, query: str, limit: int, offset: int) -> list[Group]: ...
    def count_search(self, query: str) -> int: ...


    def is_member(self, group_id: UUID, user_id: UUID) -> bool: ...


    def is_owner(self, group_id: UUID, user_id: UUID) -> bool: ...


    def name_exists(self, name: str, exclude_group_id: UUID | None = None) -> bool: ...


class GroupMemberRepository(Protocol):
    def get_by_id(self, member_id: UUID) -> GroupMember | None: ...
    def get_by_group_and_user(self, group_id: UUID, user_id: UUID) -> GroupMember | None: ...
    def list_by_group(self, group_id: UUID, limit: int, offset: int) -> list[GroupMember]: ...
    def count_by_group(self, group_id: UUID) -> int: ...
    def create(self, member: GroupMember) -> GroupMember: ...
    def update(self, member: GroupMember) -> GroupMember: ...
    def delete(self, member_id: UUID) -> None: ...
    def delete_by_group_and_user(self, group_id: UUID, user_id: UUID) -> None: ...

    def list_by_user(self, user_id: UUID) -> list[GroupMember]: ...


    def count_admins(self, group_id: UUID) -> int: ...


    def role_at_least(self, group_id: UUID, user_id: UUID, required_role: MemberRole) -> bool: ...


    def is_owner(self, group_id: UUID, user_id: UUID) -> bool: ...
    def is_admin(self, group_id: UUID, user_id: UUID) -> bool: ...
    def is_member(self, group_id: UUID, user_id: UUID) -> bool: ...


class PollRepository(Protocol):
    def get_by_id(self, poll_id: UUID) -> Poll | None: ...
    def list_by_group(self, group_id: UUID, limit: int, offset: int) -> list[Poll]: ...
    def count_by_group(self, group_id: UUID) -> int: ...
    def create(self, poll: Poll) -> Poll: ...
    def update(self, poll: Poll) -> Poll: ...
    def delete(self, poll_id: UUID) -> None: ...

    def close(self, poll_id: UUID) -> Poll: ...

    def list_open(self, group_id: UUID) -> list[Poll]: ...


class PollOptionRepository(Protocol):
    def get_by_id(self, option_id: UUID) -> PollOption | None: ...
    def list_by_poll(self, poll_id: UUID) -> list[PollOption]: ...
    def create(self, option: PollOption) -> PollOption: ...
    def update(self, option: PollOption) -> PollOption: ...
    def delete(self, option_id: UUID) -> None: ...

    def count_votes(self, option_id: UUID) -> int: ...


    def bulk_create(self, options: list[PollOption]) -> list[PollOption]: ...


    def get_top_option(self, poll_id: UUID) -> PollOption | None: ...


    def reorder(self, poll_id: UUID, option_ids: list[UUID]) -> None: ...


class PollVoteRepository(Protocol):
    def get_by_id(self, vote_id: UUID) -> PollVote | None: ...
    def get_by_poll_and_user(self, poll_id: UUID, user_id: UUID) -> PollVote | None: ...
    def list_by_poll(self, poll_id: UUID) -> list[PollVote]: ...
    def create(self, vote: PollVote) -> PollVote: ...
    def delete(self, vote_id: UUID) -> None: ...
    def delete_by_poll_and_user(self, poll_id: UUID, user_id: UUID) -> None: ...

    def has_voted(self, poll_id: UUID, user_id: UUID) -> bool: ...
    def vote_count(self, poll_id: UUID) -> int: ...

    def get_results(self, poll_id: UUID) -> dict[UUID, int]: ...


class MessageRepository(Protocol):
    def get_by_id(self, message_id: UUID) -> Message | None: ...
    def list_by_group(self, group_id: UUID, limit: int, offset: int) -> list[Message]: ...
    def count_by_group(self, group_id: UUID) -> int: ...
    def create(self, message: Message) -> Message: ...
    def delete(self, message_id: UUID) -> None: ...

    def add_reaction(self, message_id: UUID, user_id: UUID, emoji: str) -> None: ...
    def remove_reaction(self, message_id: UUID, user_id: UUID, emoji: str) -> None: ...
    def get_reactions(self, message_id: UUID) -> dict[str, list[UUID]]: ...

    def get_attachments(self, message_id: UUID) -> list[Attachment]: ...
    def link_attachment(self, message_id: UUID, attachment_id: UUID) -> None: ...


class AttachmentRepository(Protocol):
    def get_by_id(self, attachment_id: UUID) -> Attachment | None: ...
    def create(self, attachment: Attachment) -> Attachment: ...
    def delete(self, attachment_id: UUID) -> None: ...
    def list_by_group(self, group_id: UUID) -> list[Attachment]: ...


class TaskRepository(Protocol):
    def get_by_id(self, task_id: UUID) -> Task | None: ...
    def list_by_group(self, group_id: UUID, limit: int, offset: int) -> list[Task]: ...
    def count_by_group(self, group_id: UUID) -> int: ...
    def list_by_status(self, group_id: UUID, status: TaskStatus, limit: int, offset: int) -> list[Task]: ...
    def count_by_status(self, group_id: UUID, status: TaskStatus) -> int: ...
    def create(self, task: Task) -> Task: ...
    def update(self, task: Task) -> Task: ...
    def delete(self, task_id: UUID) -> None: ...

    def assign(self, task_id: UUID, user_id: UUID | None) -> Task: ...
    def mark_done(self, task_id: UUID) -> Task: ...
    def mark_pending(self, task_id: UUID) -> Task: ...


    def count_pending(self, group_id: UUID) -> int: ...
    def count_done(self, group_id: UUID) -> int: ...


class PackingItemRepository(Protocol):
    def get_by_id(self, item_id: UUID) -> PackingItem | None: ...
    def list_by_group(self, group_id: UUID, limit: int, offset: int) -> list[PackingItem]: ...
    def count_by_group(self, group_id: UUID) -> int: ...
    def list_by_category(self, group_id: UUID, category: str | None) -> list[PackingItem]: ...
    def list_packed(self, group_id: UUID) -> list[PackingItem]: ...
    def list_unpacked(self, group_id: UUID) -> list[PackingItem]: ...
    def create(self, item: PackingItem) -> PackingItem: ...
    def update(self, item: PackingItem) -> PackingItem: ...
    def delete(self, item_id: UUID) -> None: ...

    def mark_packed(self, item_id: UUID) -> PackingItem: ...
    def mark_unpacked(self, item_id: UUID) -> PackingItem: ...

    def categories(self, group_id: UUID) -> list[str]: ...
    def packing_progress(self, group_id: UUID) -> tuple[int, int]: ...