from typing import Protocol
from uuid import UUID

from app.modules.maps.models import Marker, MarkerComment, Route


class MarkerRepository(Protocol):
    def get_by_id(self, marker_id: UUID) -> Marker | None: ...
    def list_by_group(self, group_id: UUID) -> list[Marker]: ...
    def create(self, marker: Marker) -> Marker: ...
    def update(self, marker: Marker) -> Marker: ...
    def delete(self, marker_id: UUID) -> None: ...


class RouteRepository(Protocol):
    def get_by_id(self, route_id: UUID) -> Route | None: ...
    def list_by_group(self, group_id: UUID) -> list[Route]: ...
    def create(self, route: Route) -> Route: ...
    def update(self, route: Route) -> Route: ...
    def delete(self, route_id: UUID) -> None: ...


class MarkerCommentRepository(Protocol):
    def get_by_id(self, comment_id: UUID) -> MarkerComment | None: ...
    def list_by_marker(self, marker_id: UUID) -> list[MarkerComment]: ...
    def list_by_markers(self, marker_ids: list[UUID]) -> dict[UUID, list[MarkerComment]]: ...
    def create(self, comment: MarkerComment) -> MarkerComment: ...
    def update_body(self, comment_id: UUID, body: str) -> MarkerComment: ...
    def delete(self, comment_id: UUID) -> None: ...
